AllCops:
  TargetRubyVersion: 3.1.2
  TargetRailsVersion: 7.0.3
  DisplayCopNames: true
  NewCops: enable
  Exclude:
    - 'vendor/**/*'
    - 'db/*'
    - 'tmp/**/*'
    - 'bin/**/*'

require:
  - rubocop-rails
  - rubocop-faker
  - rubocop-performance

inherit_gem:
  rubocop-shopify: rubocop.yml

Style/FrozenStringLiteralComment:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: single_quotes

Lint/MissingSuper:
  Exclude:
    - 'app/services/**/*'

Style/WordArray:
  Enabled: false

Style/SymbolArray:
  Enabled: false

Rails/HttpStatus:
  Enabled: false
